name: Main Workflow

on:
  push:
    branches: [master]

jobs:
  build-test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
          cache: 'yarn'

      - name: Yarn Install
        run: yarn install --immutable

      - name: Jest Test
        run: yarn test
