name: PR - Closed

on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  delete-s3:
    name: Delete S3 Website
    runs-on: ubuntu-latest
    env:
      AWS_REGION: 'eu-central-1'
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Run Action
        uses: ./
        with:
          bucket-prefix: 's3-website-pr-action'
