name: PR

on:
  pull_request:
    branches: [master]

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Jest Test
        run: yarn test

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  test:
    name: Run Action
    needs: build-test
    runs-on: ubuntu-latest
    env:
      AWS_REGION: 'eu-central-1'
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist

      - name: Run Action
        uses: ./
        with:
          bucket-prefix: 's3-website-pr-action'
          folder-to-copy: './example-app'
